version: "3"
services:
  openapi-ui:
    image: swaggerapi/swagger-ui
    container_name: "shout-openapi-ui"
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yml
    volumes:
      - ./openapi:/openapi
  db:
    image: mysql:latest
    volumes:
      - ./backend/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306