openapi: "3.0.0"
info:
  version: 1.0.0
  title: Shout
  description: SCCP 2020 Sample Project
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserRegisterRequest:
      properties:
        screen_id:
          type: string
        name:
          type: string
        password:
          type: string
        biography:
          type: string
      required:
      - screen_id
      - name
      - password
    UserEditRequest:
      properties:
        screen_id:
          type: string
        name:
          type: string
        password:
          type: string
        biography:
          type: string
    UserLoginRequest:
      properties:
        screen_id:
          type: string
        password:
          type: string
      required:
      - screen_id
      - password
    UserLoginResponse:
      properties:
        token:
          type: string
    CreateShoutRequest:
      properties:
        content:
          type: string
        parent:
          type: string
      required:
      - content
paths:
  /users:
    post:
      summary: ユーザー登録
      operationId: userRegister
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterRequest'
      responses:
        '201':
          description: Created
        '409':
          description: screen_id already exist
    patch:
      summary: ユーザー情報編集
      operationId: userEdit
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEditRequest'
      responses:
        '201':
          description: Created
        '409':
          description: screen_id already exist
  /users/image:
    put:
      summary: ユーザープロフィール画像変更
      operationId: userImageChange
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created
  /users/login:
    post:
      summary: ユーザーログイン
      operationId: userLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
          '204':
            description: Login Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UserLoginResponse'
          '401':
            description: Login Failure
  /users/{id}/follow:
    post:
      summary: ユーザーフォロー
      operationId: userFollow
      security:
        - Bearer: []
      responses:
        '204':
          description: Follow Success
        '404':
          description: User Not Found
        '409':
          description: Already Followed
