openapi: "3.0.0"
info:
  version: 1.0.0
  title: Shout
  description: SCCP 2020 Sample Project
servers:
  - url: http://localhost:8080
components:
  schemas:
    UserRegisterRequest:
      properties:
        screen_id:
          type: string
        name:
          type: string
        password:
          type: string
        biography:
          type: string
      required:
      - screen_id
      - name
      - password
    UserEditRequest:
      properties:
        screen_id:
          type: string
        name:
          type: string
        password:
          type: string
        biography:
          type: string
    UserLoginRequest:
      properties:
        screen_id:
          type: string
        password:
          type: string
      required:
      - screen_id
      - password
    CreateShoutRequest:
      properties:
        content:
          type: string
        parent:
          type: string
      required:
      - content
paths:
  /users:
    post:
      summary: ユーザー登録
      operationId: userRegister
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterRequest'
      responses:
        '201':
          description: Created
        '409':
          description: screen_id already exist
    patch:
      summary: ユーザー情報編集
      operationId: userEdit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEditRequest'
      responses:
        '201':
          description: Created
        '409':
          description: screen_id already exist
  /users/image:
    put:
      summary: ユーザープロフィール画像変更
      operationId: userImageChange
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created
